spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317

  logs:
    exporter: otlp

  propagators: [b3, b3_multi, tracecontext, baggage]
