spring:
  application:
    name: demo
  data:
    mongodb:
      uri:
        user: mongodb://localhost:27017/webfluxdemodbuser
        item: mongodb://localhost:27017/webfluxdemodbitem
      auto-index-creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317



